'use strict'

const ukCitiesAndTowns = [
    {value: 'Unknown', label: 'Unknown'},
    {value: 'Aberdeen City', label: 'Aberdeen City'},
    {value: 'Ashford', label: 'Ashford'},
    {value: 'Barking and Dagenham', label: 'Barking and Dagenham'},
    {value: 'Barnet', label: 'Barnet'},
    {value: 'Barnsley', label: 'Barnsley'},
    {value: 'Basildon', label: 'Basildon'},
    {value: 'Basingstoke and Deane', label: 'Basingstoke and Deane'},
    {value: 'Bath and North East Somerset', label: 'Bath and North East Somerset'},
    {value: 'Bedford', label: 'Bedford'},
    {value: 'Belfast', label: 'Belfast'},
    {value: 'Bexley', label: 'Bexley'},
    {value: 'Birmingham', label: 'Birmingham'},
    {value: 'Blackburn with Darwen', label: 'Blackburn with Darwen'},
    {value: 'Blackpool', label: 'Blackpool'},
    {value: 'Bolton', label: 'Bolton'},
    {value: 'Bournemouth', label: 'Bournemouth'},
    {value: 'Bracknell Forest', label: 'Bracknell Forest'},
    {value: 'Bradford', label: 'Bradford'},
    {value: 'Brent', label: 'Brent'},
    {value: 'Brighton and Hove', label: 'Brighton and Hove'},
    {value: 'Bristol, City of', label: 'Bristol, City of'},
    {value: 'Bromley', label: 'Bromley'},
    {value: 'Burnley', label: 'Burnley'},
    {value: 'Bury', label: 'Bury'},
    {value: 'Cambridge', label: 'Cambridge'},
    {value: 'Camden', label: 'Camden'},
    {value: 'Cannock Chase', label: 'Cannock Chase'},
    {value: 'Cardiff', label: 'Cardiff'},
    {value: 'Carlisle', label: 'Carlisle'},
    {value: 'Chelmsford', label: 'Chelmsford'},
    {value: 'Cheltenham', label: 'Cheltenham'},
    {value: 'Cheshire West and Chester', label: 'Cheshire West and Chester'},
    {value: 'Chesterfield', label: 'Chesterfield'},
    {value: 'City of Edinburgh', label: 'City of Edinburgh'},
    {value: 'City of London', label: 'City of London'},
    {value: 'Colchester', label: 'Colchester'},
    {value: 'Corby', label: 'Corby'},
    {value: 'Coventry', label: 'Coventry'},
    {value: 'Crawley', label: 'Crawley'},
    {value: 'Croydon', label: 'Croydon'},
    {value: 'Dacorum', label: 'Dacorum'},
    {value: 'Darlington', label: 'Darlington'},
    {value: 'Derby', label: 'Derby'},
    {value: 'Doncaster', label: 'Doncaster'},
    {value: 'Dudley', label: 'Dudley'},
    {value: 'Dundee City', label: 'Dundee City'},
    {value: 'Ealing', label: 'Ealing'},
    {value: 'East Staffordshire', label: 'East Staffordshire'},
    {value: 'Eastbourne', label: 'Eastbourne'},
    {value: 'Eastleigh', label: 'Eastleigh'},
    {value: 'Enfield', label: 'Enfield'},
    {value: 'Exeter', label: 'Exeter'},
    {value: 'Falkirk', label: 'Falkirk'},
    {value: 'Gateshead', label: 'Gateshead'},
    {value: 'Glasgow City', label: 'Glasgow City'},
    {value: 'Gloucester', label: 'Gloucester'},
    {value: 'Gosport', label: 'Gosport'},
    {value: 'Gravesham', label: 'Gravesham'},
    {value: 'Great Yarmouth', label: 'Great Yarmouth'},
    {value: 'Greenwich', label: 'Greenwich'},
    {value: 'Guildford', label: 'Guildford'},
    {value: 'Hackney', label: 'Hackney'},
    {value: 'Halton', label: 'Halton'},
    {value: 'Hammersmith and Fulham', label: 'Hammersmith and Fulham'},
    {value: 'Haringey', label: 'Haringey'},
    {value: 'Harlow', label: 'Harlow'},
    {value: 'Hartlepool', label: 'Hartlepool'},
    {value: 'Hastings', label: 'Hastings'},
    {value: 'Havering', label: 'Havering'},
    {value: 'Hillingdon', label: 'Hillingdon'},
    {value: 'Hounslow', label: 'Hounslow'},
    {value: 'Hyndburn', label: 'Hyndburn'},
    {value: 'Harrow', label: 'Harrow'},
    {value: 'Inverclyde (Greenock)', label: 'Inverclyde (Greenock)'},
    {value: 'Ipswich', label: 'Ipswich'},
    {value: 'Islington', label: 'Islington'},
    {value: 'Kensington and Chelsea', label: 'Kensington and Chelsea'},
    {value: 'Kettering', label: 'Kettering'},
    {value: 'Kingston upon Hull, City of', label: 'Kingston upon Hull, City of'},
    {value: 'Kingston upon Thames', label: 'Kingston upon Thames'},
    {value: 'Lambeth', label: 'Lambeth'},
    {value: 'Leeds', label: 'Leeds'},
    {value: 'Leicester', label: 'Leicester'},
    {value: 'Lewisham', label: 'Lewisham'},
    {value: 'Lincoln', label: 'Lincoln'},
    {value: 'Liverpool', label: 'Liverpool'},
    {value: 'Luton', label: 'Luton'},
    {value: 'Maidstone', label: 'Maidstone'},
    {value: 'Manchester', label: 'Manchester'},
    {value: 'Mansfield', label: 'Mansfield'},
    {value: 'Medway', label: 'Medway'},
    {value: 'Merton', label: 'Merton'},
    {value: 'Middlesbrough', label: 'Middlesbrough'},
    {value: 'Milton Keynes', label: 'Milton Keynes'},
    {value: 'Newcastle upon Tyne', label: 'Newcastle upon Tyne'},
    {value: 'Newham', label: 'Newham'},
    {value: 'Newport', label: 'Newport'},
    {value: 'North East Lincolnshire', label: 'North East Lincolnshire'},
    {value: 'North Tyneside', label: 'North Tyneside'},
    {value: 'Northampton', label: 'Northampton'},
    {value: 'North Lanarkshire', label: 'North Lanarkshire'},
    {value: 'Norwich', label: 'Norwich'},
    {value: 'Nottingham', label: 'Nottingham'},
    {value: 'Nuneaton and Bedworth', label: 'Nuneaton and Bedworth'},
    {value: 'Oldham', label: 'Oldham'},
    {value: 'Oxford', label: 'Oxford'},
    {value: 'Peterborough', label: 'Peterborough'},
    {value: 'Plymouth', label: 'Plymouth'},
    {value: 'Poole', label: 'Poole'},
    {value: 'Portsmouth', label: 'Portsmouth'},
    {value: 'Preston', label: 'Preston'},
    {value: 'Reading', label: 'Reading'},
    {value: 'Redbridge', label: 'Redbridge'},
    {value: 'Redditch', label: 'Redditch'},
    {value: 'Renfrewshire (Paisley)', label: 'Renfrewshire (Paisley)'},
    {value: 'Richmond upon Thames', label: 'Richmond upon Thames'},
    {value: 'Rochdale', label: 'Rochdale'},
    {value: 'Rotherham', label: 'Rotherham'},
    {value: 'Rugby', label: 'Rugby'},
    {value: 'Rushmoor', label: 'Rushmoor'},
    {value: 'Salford', label: 'Salford'},
    {value: 'Sandwell', label: 'Sandwell'},
    {value: 'Sefton', label: 'Sefton'},
    {value: 'Sheffield', label: 'Sheffield'},
    {value: 'Slough', label: 'Slough'},
    {value: 'Solihull', label: 'Solihull'},
    {value: 'South Tyneside', label: 'South Tyneside'},
    {value: 'Southampton', label: 'Southampton'},
    {value: 'Southend-on-Sea', label: 'Southend-on-Sea'},
    {value: 'St. Albans', label: 'St. Albans'},
    {value: 'St. Helens', label: 'St. Helens'},
    {value: 'Stockport', label: 'Stockport'},
    {value: 'Stockton-on-Tees', label: 'Stockton-on-Tees'},
    {value: 'Sunderland', label: 'Sunderland'},
    {value: 'Sutton', label: 'Sutton'},
    {value: 'Swansea', label: 'Swansea'},
    {value: 'Swindon', label: 'Swindon'},
    {value: 'Tameside', label: 'Tameside'},
    {value: 'Tamworth', label: 'Tamworth'},
    {value: 'Telford and Wrekin', label: 'Telford and Wrekin'},
    {value: 'Thanet', label: 'Thanet'},
    {value: 'Thurrock', label: 'Thurrock'},
    {value: 'Torbay', label: 'Torbay'},
    {value: 'Tower Hamlets', label: 'Tower Hamlets'},
    {value: 'Trafford', label: 'Trafford'},
    {value: 'Tunbridge Wells', label: 'Tunbridge Wells'},
    {value: 'Wakefield', label: 'Wakefield'},
    {value: 'Walsall', label: 'Walsall'},
    {value: 'Waltham Forest', label: 'Waltham Forest'},
    {value: 'Wandsworth', label: 'Wandsworth'},
    {value: 'Warrington', label: 'Warrington'},
    {value: 'Warwick', label: 'Warwick'},
    {value: 'Watford', label: 'Watford'},
    {value: 'Waveney', label: 'Waveney'},
    {value: 'Westminster', label: 'Westminster'},
    {value: 'Wigan', label: 'Wigan'},
    {value: 'Wirral', label: 'Wirral'},
    {value: 'Woking', label: 'Woking'},
    {value: 'Wolverhampton', label: 'Wolverhampton'},
    {value: 'Worcester', label: 'Worcester'},
    {value: 'Worthing', label: 'Worthing'},
    {value: 'Wrexham', label: 'Wrexham'},
    {value: 'Wycombe', label: 'Wycombe'},
    {value: 'York', label: 'York'},
  ];

  module.exports = ukCitiesAndTowns;
